### ISSUE TITLE
Polymorphic Node npm module (Error: Cannot find module)

### ISSUE THREAD

**Issue by dahal** [rubyonjets/jets#436]
## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |     OSX Catalina 10.15.2    |
| Jets             |     2.3.12    |
| Ruby             |     2.5.3p105    |

---

## Expected Behaviour

* From the root directory of the project, i have installed npm module, eg: `npm i file-type --save`
* I should be able to require that npm module and use it on node files.

## Current Behavior
```js
Jets::PolyFun::NodeError:     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
        at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
        at Module.load (internal/modules/cjs/loader.js:620:32)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
        at Module._compile (internal/modules/cjs/loader.js:721:30)
        at Object.<anonymous> (/privateapp/controllers/images_controller/node/resize.js:5:18)
        at require (internal/modules/cjs/helpers.js:20:18)
        at Module.require (internal/modules/cjs/loader.js:657:17)
        at Function.Module._load (internal/modules/cjs/loader.js:529:25)
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
        Error: Cannot find module 'file-type'
```

## Step-by-step reproduction instructions
* On app root directory `npm install file-type --save`
* Defined routes, controller and node folder as according to [docs](https://rubyonjets.com/docs/polymorphic-node/)
* Required npm module on the file
* Got an error when trying to use that npm module

Here is the screenshot:

<img width="1077" alt="Issue" src="https://user-images.githubusercontent.com/3684236/73249775-61b7dd80-416a-11ea-91e2-96bddfbdfdc5.png">

**Comment by tongueroo** [comment]
Guessing this might work at the function folder. Since a polymorphic shim handler really only knows about what's in it's own folder. Closing this out to clean up issues.
